import PressRelease from "../../src/components/press-release";
import GitLabImageResource from "../../assets/img/KS-Resources-Gitlab-Partner-Content-Image-Press-Release_1366x678@3x.png"

const GitLabPressRelease = () => (
    <PressRelease
        date={'27 JULY 2021'}
        city={'CAPE TOWN, WESTERN CAPE'}
        image={GitLabImageResource}
        title="Kinetic Skunk Achieves Professional Services Partner Status with GitLab"
        description="<h1>Kinetic Skunk</h1> today announced it has achieved Professional Services Certified Partner status in the GitLab Channel Services Program. Customers rely on GitLab’s unified open DevOps platform to streamline software development complexity, increase productivity, and accelerate time to market."
        content="<p>Kinetic Skunk today announced it has achieved Professional Services Certified Partner status in the GitLab Channel Services Program. Customers rely on GitLab’s unified open DevOps platform to streamline software development complexity, increase productivity, and accelerate time to market.</p><p> As a Professional Services Certified Partner, GitLab recognises Kinetic Skunk’s demonstrated expertise and proven success in building on GitLab’s platform to transform the DevOps lifecycle. Kinetic Skunk offers testing services and solutions to businesses around South Africa and is adept at engineering flawless user-experiences with its unique approach to Continuous Testing and DevOps. Clients of Kinetic Skunk use their services in preventing software defects early to streamline development and ensure the success of their products and business reputation. “It is a privilege to be recognised as the first South African GitLab Professional Services Partner. It validates our efforts in providing a quality service to our customers and will allow us to achieve even more into the future,” said Donovan Mulder, CEO and founder of Kinetic Skunk. “We are excited to begin exploring the unique opportunities of this partnership and the benefits it will have for our customers.”</p><p> “To be competitive in the market today, companies need to transform and streamline how they develop, manage, and secure software,” said Michelle Hodges, vice president of global channels at GitLab. “The GitLab Channel Services Program arms a growing community of partners like Kinetic Skunk to extend the power of GitLab’s DevOps platform and dramatically accelerate time to market. Together with Kinetic Skunk, we are fundamentally changing the way development, security and ops teams collaborate and build software and are helping organizations accelerate their software development processes and improve automation.”</p><p> The partnership is expected to expand Kinetic Skunk’s services and solutions for their customers, helping them develop efficient, integrated end to end processes. The partnership will also enable the company to offer specialised deployment and consulting services that are officially recognised by GitLab.</p><p> To learn more about the GitLab Channel Services Program, please visit: <a href='https://about.gitlab.com/resellers/' target='_blank'>https://about.gitlab.com/resellers/</a><br> For more information on Kinetic Skunk, visit <a href='https://kineticskunk.com/'>https://kineticskunk.com/</a> </p><p><b>About Kinetic Skunk</b><br> Kinetic Skunk was founded in 2011 in Cape Town, South Africa. It is a test-left software quality assurance solutions provider that specialises in engineering Continuous Testing within DevOps environments. They have pioneered an approach to Continuous Testing to offer Early Stage Defect Detection and Prevention Solutions to their customers.</p>"
        />
);

export default GitLabPressRelease;